steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/parity-backend', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/parity-backend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - parity-backend
      - --image=gcr.io/$PROJECT_ID/parity-backend
      - --region=us-central1
      - --platform=managed
      - --memory=2Gi
      - --cpu=2
      - --allow-unauthenticated
      - --set-env-vars=PARITY_INGESTION_URL=https://parity-ingestion-gmkewhxbha-uc.a.run.app
