steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tunnel/parity-backend-prod:$COMMIT_SHA
      - .
    dir: backend

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tunnel/parity-backend-prod:$COMMIT_SHA

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - parity-backend-prod
      - --platform=managed
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tunnel/parity-backend-prod:$COMMIT_SHA
      - --region=us-central1
      - --memory=2Gi
      - --cpu=2
      - --timeout=300
      - --concurrency=80
      - --min-instances=0
      - --max-instances=3
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/tunnel/parity-backend-prod:$COMMIT_SHA
