from __future__ import annotations

from typing import List, Dict, Any

from backend.v1.core.declared_financials import DeclaredFinancials


def compute_detected_revenue(transactions: List[Dict[str, Any]]) -> int:
    """
    Computes total detected revenue (in cents).

    Deterministic rules:
    - Include only operational inflows (positive amounts).
    - Exclude transfers, loans, injections, and needs_review.
    - Exclude any non-operational revenue roles by only allowing an allow-list.
    """

    # Roles representing revenue generated by operating activity.
    # Note: classifier role names vary slightly across matchers; keep the allow-list broad but explicit.
    REVENUE_ROLES = {
        "revenue_operational",
        # Some matchers classify inbound mobile money as mpesa_inflow.
        "mpesa_inflow",
        # Possible legacy/variant roles (kept for forward compatibility).
        "revenue_pos",
        "revenue_mpesa",
        "customer_payment",
    }

    EXCLUDED_ROLES = {
        "loan",
        "loan_inflow",
        "capital_injection",
        "transfer",
        "internal_transfer",
        "needs_review",
        "supplier",
        "bank_charge",
    }

    total = 0
    for txn in transactions:
        role = txn.get("role")
        try:
            amount = int(txn.get("signed_amount_cents", 0) or 0)
        except (TypeError, ValueError):
            amount = 0

        # Only positive inflows.
        if amount <= 0:
            continue

        if role in EXCLUDED_ROLES:
            continue

        if role in REVENUE_ROLES:
            total += amount
            continue

        # default: exclude unknown roles (including revenue_non_operational, other, etc.)
        continue

    return total


def compute_revenue_explanation(transactions: list) -> dict:
    """
    Computes breakdown of included vs excluded inflows for revenue reconciliation.
    """

    # Keep aligned with compute_detected_revenue allow-list (operational inflows).
    REVENUE_ROLES = {
        "revenue_operational",
        "revenue_pos",
        "revenue_mpesa",
        "customer_payment",
        "mpesa_inflow",
    }

    excluded_breakdown = {
        "needs_review": 0,
        "transfer": 0,
        "loan": 0,
        "capital_injection": 0,
        "other": 0,
    }

    included = 0

    loan_roles = {"loan", "loan_inflow", "loan_repayment"}
    transfer_roles = {"transfer", "internal_transfer"}

    for txn in transactions:
        role = txn.get("role")
        try:
            amount = int(txn.get("signed_amount_cents", 0) or 0)
        except (TypeError, ValueError):
            amount = 0

        # Only positive inflows participate in reconciliation explanation.
        if amount <= 0:
            continue

        if role in REVENUE_ROLES:
            included += amount
        elif role == "needs_review":
            excluded_breakdown["needs_review"] += amount
        elif role in transfer_roles:
            excluded_breakdown["transfer"] += amount
        elif role in loan_roles:
            excluded_breakdown["loan"] += amount
        elif role == "capital_injection":
            excluded_breakdown["capital_injection"] += amount
        else:
            excluded_breakdown["other"] += amount

    total_excluded = sum(excluded_breakdown.values())

    return {
        "included_revenue_cents": included,
        "excluded_cents": total_excluded,
        "excluded_breakdown": excluded_breakdown,
    }


def generate_revenue_insight(explanation: dict) -> str:
    """
    Generates a human-readable insight from explanation data.

    Deterministic and integer-only. Always returns a string.
    """

    included = explanation.get("included_revenue_cents", 0) or 0
    excluded = explanation.get("excluded_cents", 0) or 0

    included = int(included)
    excluded = int(excluded)

    total = included + excluded
    if total <= 0:
        return "No inflow activity detected"

    if excluded == 0:
        return "All detected inflows appear operational"

    breakdown = explanation.get("excluded_breakdown") or {}

    # Deterministic tie-breaking: iterate keys in insertion order (dict literal upstream).
    dominant_type = None
    dominant_value = -1
    for k, v in breakdown.items():
        v_int = int(v or 0)
        if v_int > dominant_value:
            dominant_type = k
            dominant_value = v_int

    if not dominant_type:
        dominant_type = "other"

    excluded_pct = int((excluded * 100) / total)
    return f"{excluded_pct}% of inflows excluded as {dominant_type}"


def compute_reconciliation(
    declared: DeclaredFinancials,
    transactions: list,
) -> dict:
    """
    Reconciles declared financials vs detected bank activity.

    Currently supports revenue.
    Structured for future expansion (expenses, profit, multi-period).
    """

    detected_revenue = compute_detected_revenue(transactions)
    declared_revenue = declared.total_revenue()
    explanation = compute_revenue_explanation(transactions)
    insight = generate_revenue_insight(explanation)

    delta = detected_revenue - declared_revenue

    if declared_revenue == 0:
        return {
            "revenue": {
                "detected_cents": detected_revenue,
                "declared_cents": declared_revenue,
                "delta_cents": None,
                "delta_bps": None,
                "status": "INSUFFICIENT_DATA",
                "explanation": explanation,
                "insight": insight,
            }
        }

    delta_bps = int((delta * 10000) / declared_revenue)

    abs_delta_bps = abs(delta_bps)

    if abs_delta_bps <= 1000:
        status = "MATCH"
    elif abs_delta_bps <= 2500:
        status = "NEEDS_REVIEW"
    else:
        status = "MISMATCH"

    return {
        "revenue": {
            "detected_cents": detected_revenue,
            "declared_cents": declared_revenue,
            "delta_cents": delta,
            "delta_bps": delta_bps,
            "status": status,
            "explanation": explanation,
            "insight": insight,
        }
    }

